rinigus/pure-maps

- qml/IconListItem.qml
- qml/Map.qml
- qml/PoiInfoPage.qml
- qml/PoiPage.qml
- qml/PoiPanel.qml
- qml/RoutePointPage.qml
- qml/platform.qtcontrols/DialogListPL.qml
- qml/platform.qtcontrols/DialogPL.qml
- qml/platform.qtcontrols/StylerPL.qml
- qml/platform.silica/StylerPL.qml
Allows to shortlist POIs, fixing #59 
In addition, updates all POI details, as they are changed. Fixes #71
> add shortlisted POIs

- packaging/ubports/README.md
- packaging/ubports/manifest.json
Adjusts version to 1.22. Also comments on a Python issue in README.
> Adjust version in Ubports package

- packaging/ubports/README.md
- packaging/ubports/clickable.json
- packaging/ubports/install-deps.sh
- packaging/ubports/prepare-deps.sh
This builds and ships mimic with the Ubuntu Touch package.
- Building mimic takes 45min on my (rather old) machine
- Click package with mimic is 85 MB in size
> Package Mimic with Ubuntu Touch Package

- packaging/ubports/clickable.json
- packaging/ubports/install-deps.sh
- packaging/ubports/prepare-deps.sh
This builds and ships picotts with the Ubuntu Touch package.
- Click package with mimic is 8 MB in size
> Package PicoTTS with Ubuntu Touch Package

- .gitignore
- packaging/ubports/clickable-silent.json
- packaging/ubports/install-deps.sh
- packaging/ubports/prepare-deps.sh
This adds a silent clickable configuration for packaging the Ubuntu Touch package without TTS.
> Add silent clickable configuration

- qml/PreferencesPage.qml
Minor fix adding OpenStore to info text on TTS.
> Fix info on TTS to include OpenStore

- packaging/ubports/clickable.json
- packaging/ubports/install-deps.sh
- packaging/ubports/manifest.json
Fixes #320 and increments version patch for the patch release on the open store that also fixes pasting API keys.
> Specify icon with file extension

- packaging/ubports/prepare-deps.sh
Just a minor fix in the dependencies download script.
> Fix broken link in ubports prepare deps script

- packaging/ubports/pure-maps.apparmor
- qml/platform.ubports/FileSelectorPL.qml
- qml/platform.ubports/StackPL.qml
#324 Implements the GPX file selector based on UT's Content Hub. Has been successfully tested by various persons from the community.
> Get gpx file import working for ut version

- packaging/ubports/clickable.json
- packaging/ubports/prepare-deps.sh
Update Mapbox in Ubuntu Touch build as requested in https://github.com/rinigus/pure-maps/issues/390.
> Update Mapbox in Ubuntu Touch

- packaging/ubports/full-build.json
- packaging/ubports/manifest.json
- packaging/ubports/slim-build.json
Fix slim build by fixing manifest and make call.
> Fix Ubports slim build

- qml/platform.ubports/TextFieldPL.qml
> [ubports] use display text to update text field

- packaging/ubports/full-build.json
- packaging/ubports/launch.sh
- packaging/ubports/pure-maps.desktop
- packaging/ubports/slim-build.json
- pure-maps.pro
> Switch Clickable config to QMake

- README.md
- po/pure-maps.pot
- poor/__init__.py
- poor/application.py
- poor/narrative.py
- poor/router.py
- pure-maps.pro
- qml/AttributionPage.qml
- qml/Map.qml
- qml/NarrativeItem.qml
- qml/NavigationCurrentBlock.qml
- qml/NavigationOverviewBlock.qml
- qml/NavigationPage.qml
- qml/Navigator.qml
- qml/PositionSourceMapMatched.qml
- qml/PreferencesPage.qml
- qml/Voice.qml
- qml/js/util.js
- qml/pure-maps.qml
- rpm/harbour-pure-maps.spec
- src/main.cpp
- src/maneuver.cpp
- src/maneuver.h
- src/maneuvermodel.cpp
- src/maneuvermodel.h
- src/navigator.cpp
- src/navigator.h
- src/prompt.cpp
- src/prompt.h
- tools/update-translations
> Rewrite of navigation engine

- packaging/ubports/full-build.json
- packaging/ubports/prepare-deps.sh
- packaging/ubports/slim-build.json
Adds s2geometry to Clickable config.
Fixes #437
> Add s2geometry to ubports build

- data/pure-maps.desktop
- packaging/pure-maps.appdata.xml
This makes the app visible in the PureOS Store on the Librem 5.
See https://puri.sm/posts/specify-form-factors-in-your-librem-5-apps/
> Add form factors to desktop and appdata files

- packaging/click/full-build.json
- packaging/click/slim-build.json
Remove map matching CMake options from click packaging config
> Clean up click packaging config

- data/harbour-pure-maps-jolla-store.desktop
Fixes #621, patch suggested by @ehdis, target file requested by @rinigus.
> Allow access to Downloads

- packaging/click/full-build.yaml
- packaging/click/pure-maps.apparmor
- packaging/click/pure-maps.desktop
- packaging/click/slim-build.yaml
- qml/platform.uuitk/ClipboardPL.qml
- qml/platform.uuitk/FileSelectorPL.qml
- qml/platform.uuitk/HeaderBarImpl.qml
- qml/platform.uuitk/IconButtonPL.qml
- qml/platform.uuitk/IconPL.qml
- qml/platform.uuitk/PageMenuItemPL.qml
- qml/platform.uuitk/PageMenuPL.qml
- qml/platform.uuitk/README.md
- qml/platform.uuitk/SearchFieldPL.qml
- qml/platform.uuitk/StylerPL.qml
- qml/platform.uuitk/TextAreaPL.qml
- qml/platform.uuitk/TextFieldPL.qml
This MR changes the click target from Ubuntu 16.04 to 20.04.
> Package click for Ubuntu Touch 20.04 (Focal)

- README.md
Minimalist information about translations. Please feel free to edit and add information.
> Create a section for translations README.md
