rinigus/pure-maps

qml/platform.qtcontrols/ApplicationWindowPL.qml
qml/platform.silica/ApplicationWindowPL.qml
qml/pure-maps.qml

PR showing what I meant in issue #90.
I wasn't yet able to test it myself because of the api keys and the handcrafted Makefile, so yeah, it's as-is :)
Basically, the platform AppWindows now have a keepAlive property that is bound there to a platform implementation of keeping alive the app, and in the pure-maps.qml that AppWindow property is bound to the conditions pure-maps wants (from the settings & application mode)

keepalive: replace explicit event handlers with property binding (#90)

---

packaging/flatpak/README.md

Looks like flatpak-builder does not download the platform and SDK
automatically, so it seems like a good idea to include instructions
how to install the Flathub repo & how to install the required platform
and SDK in the Pure Maps flatpak building docs.

Add platform and SDK download instructions to flatpak docs

---

data/pure-maps

Bash isn't actually required to run the script, any POSIX compatible shell will do.

Linux exe: replace Bash shebang for POSIX sh

---

maps/opentopomap.json

I like this one because its rendering is most similar to how the [most popular Czech topo maps issued by KČT](https://kct.cz/mapy-kct) look like. It also includes contour lines.
The only downside is that the online web app gets the path data from Longvia, and I have no clue how to add this overlay to Pure Maps.
I also don't know whether the Scout server supports multi-hostname URLs (`a.tiles.`.., `b.tiles.`..., etc).

Add an online map from OpenTopoMap.org

---

qml/platform.qtcontrols/SearchFieldPL.qml

This is a change that fixes an issue where the system spellchecking/auto suggest is conflicting with ontextchanged - resulting in the user having to press the spacebar twice to enter a space. Since the search auto suggest is suggesting results, and most street names/numbers arern't as beneficial to autocorrect ( may correct to wrong) disabling predictivetext may be good here.
The alternative may be to use ontextcompleted (i think is what was called), but that would delay suggestions until return was hit.

[ubports] fixes bug with having to hit space twice

---

packaging/ubports/clickable.json
packaging/ubports/manifest.json
packaging/ubports/pure-maps.apparmor

This PR 
- removes AppArmor permission we should not need
- fixes the Click package maintainer name :smile:

Fix policies and Maintainer name

---

data/pure-maps.desktop

This flag is needed to publish Pure Maps in the Open Store.

Add Ubuntu Touch flag to desktop file

---

packaging/ubports/README.md
packaging/ubports/clickable.json
packaging/ubports/manifest.json

Allow building arm64  and amd64 click packges besides armhf. Requires a [Clickable patch](https://gitlab.com/clickable/clickable/merge_requests/192).

Multi arch support on Ubuntu Touch

---

tools/manage-keys

Without specifying encoding the script does not work in the Clickable docker containers. This change prevents the setup to break with an upcoming change in Clickable.

Specify encoding on keys file

---

packaging/ubports/clickable.json

I used a Clickable-provided placeholder in a place, where it cannot be used(, yet). Therefore I need to revert this for now.

Fix building ubports dependencies

---

.gitignore
packaging/ubports/README.md
packaging/ubports/clickable.json

Update clickable.json to Clickable 6.13.0 and remove Python 2 instructions from UBports packaging README.

Clickable update

---

packaging/ubports/manifest.json

Open Store displays the `maintainer` from `manifest.json` as Author.

Change Open Store Author to Rinigus

---

packaging/ubports/clickable.json

Just did a fresh build for the release and figured that some install path needed to be adjusted.

Ubports: Fix nemo qml plugin install path

---

packaging/ubports/full-build.json
packaging/ubports/pure-maps.desktop
packaging/ubports/slim-build.json

This changes the name in Lomiris launcher according to the name of the app as displayed in the OpenStore.

Change app name in desktop file for different UBports versions

---

tools/check-json

`python` refers to `python2` in some distributions which we don't want.

Explicitly invoke python3 in check-json

---

packaging/click/full-build.json
packaging/click/manifest.json
packaging/click/slim-build.json

The click review tool got stricter on importing modules without specifying a framework that guarantees those. Let's let Clickable set the framework field automatically.

Let clickable set framework version in click package manifest

---

maps/openslopemap.json

A map that is useful for skiing and other mountain activity to judge
avalanche risk.
Closes: #496
Signed-off-by: Henning Schild <henning@hennsch.de>

maps: add online map for openslopemap

---

packaging/pure-maps.appdata.xml

The GPL-3.0+ SPDX licence identifier has been deprecated in favour
of GPL-3.0-or-later, so let's replace it with that.
See:
- https://spdx.org/licenses/GPL-3.0+
- https://spdx.org/licenses/GPL-3.0-or-later

Replace GPL-3.0+ licence identifier with GPL-3.0-or-later

---

data/pure-maps
packaging/click/full-build.json
packaging/click/launch.sh
packaging/click/pure-maps.desktop
packaging/click/slim-build.json

Fixes #467. This has been tested on the Ubuntu Touch dev channel.
Please wait with merging until [OTA 16](https://github.com/orgs/ubports/projects/25#card-50989623) is released to avoid breaking audio for our Ubuntu Touch users for the time being. I will send a ping here once ready.

Remove tmp in cache workaround for Ubuntu Touch

---

CMakeLists.txt
RELEASING.md
poor/CMakeLists.txt
qml/CMakeLists.txt
src/CMakeLists.txt
thirdparty/CMakeLists.txt

/cc @PureTryOut 
Source files are defined in the main folder making it possible to show
them all in the same hierarchy under Qt Creator.
Some reordering of cmake file content was done to push user-specified options to the top
and automatic processing to the later stages. Where feasible, install was done by file
listings as generated by cmake.

Adjust CMake for better Qt Creator support

---

maps/thunderforest_outdoors.json

This layer is quite similar to OpenCycleMap but in my opinion a lot better for hiking.
https://www.thunderforest.com/maps/outdoors/

add thunderforest outdoors map

---

CMakeLists.txt
poor/magfield.py
thirdparty/CMakeLists.txt

Add a CMake build option for using the geomag python module from system directories. Also, try to import first the bundled geomag module and if that fails, try the system provided one.
This is patch is used in the WIP Debian packages of pure-maps [here](https://salsa.debian.org/Mobian-team/puremaps-packaging).

CMake: Add USE_BUNDLED_GEOMAG option

---

data/harbour-pure-maps.desktop

Directories needs to end with slash. Tested with My Backup 1.0.5. 
When ending slash is missing, My Backup just skip it and logs:
/home/defaultuser/.config/harbour-pure-maps is not a file

fix My Backup configuration

---

packaging/pure-maps.appdata.xml

Otherwise generating the distribution metainfo fails: https://appstream.alpinelinux.org/html/edge/community/issues/pure-maps.html

[packaging] Correctly reference the installed desktop file

---

packaging/click/full-build.yaml
packaging/click/patches/maplibre-gl-native/disable-armhf-version-check.patch
packaging/click/patches/maplibre-gl-native/fix-compilation-with-clickable.patch
packaging/click/prepare-deps.sh
packaging/click/slim-build.yaml

This PR
- updates maplibre-gl-native patches to work with latest main branch
- updates mapbox-gl-qml to 2.1.0
- removes clickable instructions to update CMake, because Clickable now ships recent CMake 3.22.3

Update click packaging

---

.gitignore
packaging/click/prepare-deps.sh

Updates mapbox gl qml plugin to 2.1.1 in click package to address https://github.com/maplibre/maplibre-gl-native/issues/548.
Also updates gitignore file to account for the renamed clickable project config file.

Update mapbox gl qml to 2.1.1 in click package

---

packaging/click/full-build.yaml
packaging/click/slim-build.yaml

Picotts' makefile doesn't see a need to install again (`make: 'install' is up to date.`) when asked to. Touching the file ensures it is indeed installed.
The issue being solved here can be reproduced by building twice in a row:
```bash
clickable build --libs picotts
clickable build --libs picotts
```
Then `build/x86_64-linux-gnu/picotts/install/` is empty.

Ensure pico2wave is installed in click build

---

qml/PoiBlock.qml

This is a workaround for #640 (caused by [this upstream bug](https://gitlab.com/ubports/development/core/lomiri-ui-toolkit/-/issues/28)) that works as long as the app does not get resized to a very small width an back.

Add workaround for squeezed icons on UT

---

maps/osgb_outdoor.json
maps/osgb_roads.json
poor/apikeys.py
poor/keystore.py

This adds json files for the Ordnance Survey maps API (https://www.ordnancesurvey.co.uk/products/os-maps-api#get) for used in mixed or online mode. An api key definition for these maps is added to the keystore and apikeys .py files 
These map tiles are available on a free plan (with an API key signup process). They provide a reasonable level of detail and are useful if OSM Scout is not installed. They do only cover the UK.

Add Ordnance Survey (UK) maps

---

CMakeLists.txt
src/CMakeLists.txt

This fixes build failure with s2geometry 0.11.1.

cmake: Add find_package() call for S2

---

packaging/click/full-build.yaml
packaging/click/patches/abseil/0002-Remove-maes-option-from-cross-compilation.patch
packaging/click/prepare-deps.sh
packaging/click/slim-build.yaml

Switch to upstream s2geometry v0.11.1 due to #677 for click build and add transient abseil dependency.

Switch s2geometry to upstream v0.11.1 for click build

---

packaging/click/full-build.yaml
packaging/click/patches/maplibre-gl-native/add-some-missing-cstdint-inclusions-872-874.patch
packaging/click/patches/maplibre-gl-native_eternal/missing-include.patch
packaging/click/patches/mimic/fix-compilation.patch
packaging/click/prepare-deps.sh
packaging/click/pure-maps.apparmor
packaging/click/slim-build.yaml

The build config is made in a way that it should still be possible to target Ubuntu Touch 20.04 by setting the env var `CLICKABLE_FRAMEWORK` accordingly.

Let click package target Ubuntu Touch 24.04
